// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAupGMMLGZ0jftIlL3LH-AGqpBXrhpmLx4',
    appId: '1:433295944361:android:c493fdf444bd6d901fd7b8',
    messagingSenderId: '433295944361',
    projectId: 'api-6985506555347129704-25057',
    databaseURL: 'https://api-6985506555347129704-25057.firebaseio.com',
    storageBucket: 'api-6985506555347129704-25057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDehXPQQdz4CjStXrZ6nWC5sgsq30UPfkY',
    appId: '1:433295944361:ios:b512307cbf7eaf611fd7b8',
    messagingSenderId: '433295944361',
    projectId: 'api-6985506555347129704-25057',
    databaseURL: 'https://api-6985506555347129704-25057.firebaseio.com',
    storageBucket: 'api-6985506555347129704-25057.appspot.com',
    iosClientId: '433295944361-b8ns8hdnamauojtjsrq08t288e2m2nk2.apps.googleusercontent.com',
    iosBundleId: 'org.insidechassidus.insidechassidus',
  );
}
